__create__(TNOM, 2.7E+01) __COMMA__
__create2__(RCX, 0.0) __COMMA__
__create2__(RCI, 0.0) __COMMA__
__create2__(VO, 0.0) __COMMA__
__create2__(GAMM, 0.0) __COMMA__
__create__(HRCF, 1.0) __COMMA__
__create2__(RBX, 0.0) __COMMA__
__create2__(RBI, 0.0) __COMMA__
__create2__(RE, 0.0) __COMMA__
__create2__(RS, 0.0) __COMMA__
__create2__(RBP, 0.0) __COMMA__
__create2__(IS, 1.0E-16) __COMMA__
__create2__(NF, 1.0) __COMMA__
__create2__(NR, 1.0) __COMMA__
__create__(FC, 0.9) __COMMA__
__create__(CBEO, 0.0) __COMMA__
__create2__(CJE, 0.0) __COMMA__
__create2__(PE, 0.75) __COMMA__
__create__(ME, 0.33) __COMMA__
__create__(AJE, -.5) __COMMA__
__create__(CBCO, 0.0) __COMMA__
__create2__(CJC, 0.0) __COMMA__
__create__(QCO, 0.0) __COMMA__
__create2__(CJEP, 0.0) __COMMA__
__create2__(PC, 0.75) __COMMA__
__create__(MC, 0.33) __COMMA__
__create__(AJC, -.5) __COMMA__
__create2__(CJCP, 0.0) __COMMA__
__create2__(PS, 0.75) __COMMA__
__create__(MS, 0.33) __COMMA__
__create__(AJS, -.5) __COMMA__
__create2__(IBEI, 1.0E-18) __COMMA__
__create__(WBE, 1.0) __COMMA__
__create__(NEI, 1.0) __COMMA__
__create2__(IBEN, 0.0) __COMMA__
__create__(NEN, 2.0) __COMMA__
__create2__(IBCI, 1.0E-16) __COMMA__
__create__(NCI, 1.0) __COMMA__
__create2__(IBCN, 0.0) __COMMA__
__create__(NCN, 2.0) __COMMA__
__create__(AVC1, 0.0) __COMMA__
__create2__(AVC2, 0.0) __COMMA__
__create2__(ISP, 0.0) __COMMA__
__create__(WSP, 1.0) __COMMA__
__create__(NFP, 1.0) __COMMA__
__create2__(IBEIP, 0.0) __COMMA__
__create2__(IBENP, 0.0) __COMMA__
__create2__(IBCIP, 0.0) __COMMA__
__create__(NCIP, 1.0) __COMMA__
__create2__(IBCNP, 0.0) __COMMA__
__create__(NCNP, 2.0) __COMMA__
__create__(VEF, 0.0) __COMMA__
__create__(VER, 0.0) __COMMA__
__create__(IKF, 0.0) __COMMA__
__create__(IKR, 0.0) __COMMA__
__create__(IKP, 0.0) __COMMA__
__create__(TF, 0.0) __COMMA__
__create__(QTF, 0.0) __COMMA__
__create__(XTF, 0.0) __COMMA__
__create__(VTF, 0.0) __COMMA__
__create__(ITF, 0.0) __COMMA__
__create__(TR, 0.0) __COMMA__
__create__(TD, 0.0) __COMMA__
__create__(KFN, 0.0) __COMMA__
__create__(AFN, 1.0) __COMMA__
__create__(BFN, 1.0) __COMMA__
__create__(XRE, 0.0) __COMMA__
__create__(XRB, 0.0) __COMMA__
__create__(XRC, 0.0) __COMMA__
__create__(XRS, 0.0) __COMMA__
__create__(XVO, 0.0) __COMMA__
__create__(EA, 1.12) __COMMA__
__create__(EAIE, 1.12) __COMMA__
__create__(EAIC, 1.12) __COMMA__
__create__(EAIS, 1.12) __COMMA__
__create__(EANE, 1.12) __COMMA__
__create__(EANC, 1.12) __COMMA__
__create__(EANS, 1.12) __COMMA__
__create__(XIS, 3.0) __COMMA__
__create__(XII, 3.0) __COMMA__
__create__(XIN, 3.0) __COMMA__
__create__(TNF, 0.0) __COMMA__
__create__(TAVC, 0.0) __COMMA__
__create__(RTH, 0.0) __COMMA__
__create__(CTH, 0.0)
#undef __create__
#undef __create2__
#undef __COMMA__
