name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up vcpkg
      uses: lukka/get-cmake@latest
      with:
        vcpkgArgs: 'boost'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
