name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. 2>&1 | tee cmake_output.log
        make 2>&1 | tee make_output.log

    - name: Run tests
      run: |
        cd build
        ctest 2>&1 | tee ctest_output.log

    - name: Show build logs
      if: always()
      run: |
        echo "CMake Output:"
        cat build/cmake_output.log
        echo "Make Output:"
        cat build/make_output.log
        echo "CTest Output:"
        cat build/ctest_output.log
