name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
      continue-on-error: true

    - name: Run tests
      run: |
        cd build
        ctest
      continue-on-error: true

    - name: Show build logs
      if: failure()
      run: |
        cat $(find build -type f -name '*.log')
